DROP DATABASE IF EXISTS fyyur;
DROP USER IF EXISTS student;
CREATE DATABASE fyyur;
CREATE USER student WITH ENCRYPTED PASSWORD 'student';
GRANT ALL PRIVILEGES ON DATABASE fyyur TO student;
ALTER USER student CREATEDB;
ALTER USER student WITH SUPERUSER;